In [1]:
import numpy as np
from numpy import genfromtxt

In [3]:
data = genfromtxt('/home/wanakin/DATA/bank_note_data.txt',delimiter=',')

In [4]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [5]:
labels = data[:,4]

In [6]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [7]:
features = data[:,0:4]

In [8]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [9]:
X = features
y = labels

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.33,random_state=42)

In [11]:
len(X_train)

919

In [12]:
len(X_test)

453

In [15]:
len(X)

1372

In [17]:
X_train.max()

17.9274

In [18]:
X_train.min()

-13.7731

In [19]:
from sklearn.preprocessing import MinMaxScaler

In [20]:
scaler_object = MinMaxScaler()

In [22]:
X_train

array([[-0.8734  , -0.033118, -0.20165 ,  0.55774 ],
       [ 2.0177  ,  1.7982  , -2.9581  ,  0.2099  ],
       [-0.36038 ,  4.1158  ,  3.1143  , -0.37199 ],
       ...,
       [-7.0364  ,  9.2931  ,  0.16594 , -4.5396  ],
       [-3.4605  ,  2.6901  ,  0.16165 , -1.0224  ],
       [-3.3582  , -7.2404  , 11.4419  , -0.57113 ]])

In [25]:
scaler_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [26]:
scaled_X_train = scaler_object.transform(X_train)

In [27]:
scaled_X_test = scaler_object.transform(X_test)

In [28]:
from keras.models import Sequential
from keras.layers import Dense

Using TensorFlow backend.


In [29]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))
model.add(Dense(8,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

In [30]:
model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])

In [35]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.0272 - acc: 0.9913
Epoch 2/50
 - 0s - loss: 0.0269 - acc: 0.9891
Epoch 3/50
 - 0s - loss: 0.0270 - acc: 0.9891
Epoch 4/50
 - 0s - loss: 0.0274 - acc: 0.9891
Epoch 5/50
 - 0s - loss: 0.0267 - acc: 0.9891
Epoch 6/50
 - 0s - loss: 0.0273 - acc: 0.9859
Epoch 7/50
 - 0s - loss: 0.0279 - acc: 0.9859
Epoch 8/50
 - 0s - loss: 0.0272 - acc: 0.9880
Epoch 9/50
 - 0s - loss: 0.0274 - acc: 0.9891
Epoch 10/50
 - 0s - loss: 0.0274 - acc: 0.9859
Epoch 11/50
 - 0s - loss: 0.0264 - acc: 0.9891
Epoch 12/50
 - 0s - loss: 0.0266 - acc: 0.9902
Epoch 13/50
 - 0s - loss: 0.0265 - acc: 0.9913
Epoch 14/50
 - 0s - loss: 0.0271 - acc: 0.9902
Epoch 15/50
 - 0s - loss: 0.0276 - acc: 0.9880
Epoch 16/50
 - 0s - loss: 0.0270 - acc: 0.9891
Epoch 17/50
 - 0s - loss: 0.0260 - acc: 0.9891
Epoch 18/50
 - 0s - loss: 0.0259 - acc: 0.9902
Epoch 19/50
 - 0s - loss: 0.0265 - acc: 0.9913
Epoch 20/50
 - 0s - loss: 0.0263 - acc: 0.9891
Epoch 21/50
 - 0s - loss: 0.0258 - acc: 0.9902
Epoch 22/50
 - 0s - lo

In [38]:
model.metrics_names

['loss', 'acc']

In [39]:
from sklearn.metrics import confusion_matrix,classification_report

In [40]:
predictions = model.predict_classes(scaled_X_test)

In [41]:
confusion_matrix(y_test,predictions)

array([[254,   3],
       [  2, 194]])

In [42]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.99      0.99      0.99       257
        1.0       0.98      0.99      0.99       196

avg / total       0.99      0.99      0.99       453



In [43]:
model.save('BankNoteModel.h5')

In [44]:
# from keras.models import load_model
# model = load_model('BankNoteModel.h5')